Vagrant.configure("2") do |config|
    # app server
    config.vm.define "dseng" do |dseng|
      dseng.vm.box = "ubuntu/bionic64" # ubuntu/bionic64
      dseng.vm.network "forwarded_port", guest: 3000, host: 3000 # forward port 3000 to host 3000
      dseng.vm.synced_folder "../../", "/dseng" # sync folder with host
      dseng.vm.provision :shell, :path => "./app.sh" # run script on boot
    end
  end